SET SERVEROUTPUT ON;
CLEAR SCREEN;
DROP TABLE A2ERROREVENT CASCADE CONSTRAINTS;
/
CREATE TABLE A2ERROREVENT (
    ERRORID INTEGER,
    SOURCE_ROWID ROWID,
    SOURCE_TABLE VARCHAR2(30),
    ERRORCODE INTEGER,
    FILTERID INTEGER,
    DATETIME DATE,
    ACTION VARCHAR2(6),
    CONSTRAINT ERROREVENTACTION 
    CHECK (ACTION IN ('SKIP','MODIFY'))
    );
/
DROP SEQUENCE A2ERROREVENT_SEQ;
CREATE SEQUENCE A2ERROREVENT_SEQ;
/
DROP TABLE DWPROD CASCADE CONSTRAINTS;
DROP TABLE DWCUST CASCADE CONSTRAINTS;
DROP TABLE DWSALE CASCADE CONSTRAINTS;
/
CREATE TABLE DWPROD (
    DWPRODID INTEGER,
    DWSOURCETABLE VARCHAR2(30),
    DWSOURCEID INTEGER,
    PRODNAME VARCHAR2(100),
    PRODCATNAME VARCHAR2(100),
    PRODMANUNAME VARCHAR2(100),
    PRODSHIPNAME VARCHAR2(100),
    PRIMARY KEY (DWPRODID)
);
/
CREATE TABLE DWCUST (
    DWCUSTID INTEGER,
    DWSOURCEIDBRIS INTEGER,
    DWSOURCEIDMELB INTEGER,
    FIRSTNAME VARCHAR2(100),
    SURNAME VARCHAR2(100),
    GENDER VARCHAR2(1),
    PHONE INTEGER,
    POSTCODE INTEGER,
    CITY VARCHAR2(30),
    "STATE" VARCHAR2(10),
    CUSTCATNAME VARCHAR2(100),
    PRIMARY KEY (DWCUSTID)
);
/
CREATE TABLE DWSALE (
    DWSALEID INTEGER,
    DWCUSTID INTEGER,
    DWPRODID INTEGER,
    DWSOURCEIDBRIS INTEGER,
    DWSOURCEIDMELB INTEGER,
    QTY INTEGER,
    SALE_DWDATEID INTEGER,
    SHIP_DWDATEID INTEGER,
    SALEPRICE INTEGER,
    PRIMARY KEY (DWSALEID)
);
/
DROP SEQUENCE DWPROD_SEQ;
CREATE SEQUENCE DWPROD_SEQ;
DROP SEQUENCE DWCUST_SEQ;
CREATE SEQUENCE DWCUST_SEQ;
/
DROP TABLE GENDERSPELLING CASCADE CONSTRAINTS;
/
CREATE TABLE GENDERSPELLING (
    INVALIDVALUE VARCHAR(30),
    NEWVALUE VARCHAR(1)
);
/
INSERT INTO GENDERSPELLING (INVALIDVALUE, NEWVALUE) VALUES
('MAIL', 'M');
INSERT INTO GENDERSPELLING (INVALIDVALUE, NEWVALUE) VALUES
('WOMAN', 'F');
INSERT INTO GENDERSPELLING (INVALIDVALUE, NEWVALUE) VALUES
('FEM', 'F');
INSERT INTO GENDERSPELLING (INVALIDVALUE, NEWVALUE) VALUES
('FEMALE', 'F');
INSERT INTO GENDERSPELLING (INVALIDVALUE, NEWVALUE) VALUES
('MALE', 'M');
INSERT INTO GENDERSPELLING (INVALIDVALUE, NEWVALUE) VALUES
('GENTLEMAN', 'M');
INSERT INTO GENDERSPELLING (INVALIDVALUE, NEWVALUE) VALUES
('MM', 'M');
INSERT INTO GENDERSPELLING (INVALIDVALUE, NEWVALUE) VALUES
('FF', 'F');
INSERT INTO GENDERSPELLING (INVALIDVALUE, NEWVALUE) VALUES
('FEMAIL', 'F');
/
DROP SEQUENCE GENDERSPELLING_SEQ;
CREATE SEQUENCE GENDERSPELLING_SEQ;   
/
INSERT INTO A2ERROREVENT( ERRORID, SOURCE_ROWID, SOURCE_TABLE, FILTERID, DATETIME, ERRORCODE, ACTION )
SELECT A2ERROREVENT_SEQ.NEXTVAL AS ERRORID, ROWID, 'A2PRODUCT', 1, CURRENT_TIMESTAMP, 105, 'SKIP'
FROM A2PRODUCT p
WHERE p.PRODNAME IS NULL;
COMMIT;
/
INSERT INTO A2ERROREVENT ( ERRORID, SOURCE_ROWID, SOURCE_TABLE, FILTERID, DATETIME, ERRORCODE, ACTION )
SELECT A2ERROREVENT_SEQ.NEXTVAL AS ERRORID, ROWID, 'A2PRODUCT', 2, CURRENT_TIMESTAMP, 131, 'MODIFY'
FROM A2PRODUCT p
WHERE p.MANUFACTURERCODE IS NULL;
COMMIT;
/
INSERT INTO A2ERROREVENT ( ERRORID, SOURCE_ROWID, SOURCE_TABLE, FILTERID, DATETIME, ERRORCODE, ACTION )
SELECT A2ERROREVENT_SEQ.NEXTVAL AS ERRORID, ROWID, 'A2PRODUCT', 3, CURRENT_TIMESTAMP, 146, 'MODIFY'
FROM A2PRODUCT p
WHERE p.PRODCATEGORY IS NULL OR p.PRODCATEGORY NOT IN (SELECT c.PRODUCTCATEGORY FROM A2PRODCATEGORY c );
COMMIT;
/
INSERT INTO DWPROD (DWPRODID, DWSOURCETABLE, DWSOURCEID, PRODNAME, PRODCATNAME, PRODMANUNAME, PRODSHIPNAME )
SELECT DWPROD_SEQ.NEXTVAL AS DWPRODID, 'A2PRODUCT', A2PRODUCT.PRODID, A2PRODUCT.PRODNAME, A2PRODCATEGORY.CATEGORYNAME, A2MANUFACTURER.MANUNAME, A2SHIPPING.DESCRIPTION
FROM A2PRODUCT
INNER JOIN A2PRODCATEGORY ON A2PRODUCT.PRODCATEGORY = A2PRODCATEGORY.PRODUCTCATEGORY
INNER JOIN A2MANUFACTURER ON A2PRODUCT.MANUFACTURERCODE = A2MANUFACTURER.MANUCODE
INNER JOIN A2SHIPPING ON A2PRODUCT.SHIPPINGCODE = A2SHIPPING.SHIPPINGCODE
WHERE A2PRODUCT.ROWID NOT IN (SELECT e.SOURCE_ROWID FROM A2ERROREVENT e);
COMMIT;
/
INSERT INTO DWPROD (DWPRODID, DWSOURCETABLE, DWSOURCEID, PRODNAME, PRODCATNAME, PRODMANUNAME, PRODSHIPNAME )
SELECT DWPROD_SEQ.NEXTVAL AS DWPRODID, 'A2PRODUCT', A2PRODUCT.PRODID, A2PRODUCT.PRODNAME, A2PRODCATEGORY.CATEGORYNAME, 'UNKNOWN', A2SHIPPING.DESCRIPTION
FROM A2PRODUCT
INNER JOIN A2PRODCATEGORY ON A2PRODUCT.PRODCATEGORY = A2PRODCATEGORY.PRODUCTCATEGORY
INNER JOIN A2SHIPPING ON A2PRODUCT.SHIPPINGCODE = A2SHIPPING.SHIPPINGCODE
WHERE A2PRODUCT.ROWID IN (SELECT e.SOURCE_ROWID FROM A2ERROREVENT e WHERE FILTERID = 2 );
COMMIT;
/
INSERT INTO DWPROD (DWPRODID, DWSOURCETABLE, DWSOURCEID, PRODNAME, PRODCATNAME, PRODMANUNAME, PRODSHIPNAME )
SELECT DWPROD_SEQ.NEXTVAL AS DWPRODID, 'A2PRODUCT', A2PRODUCT.PRODID, A2PRODUCT.PRODNAME, 'UNKNOWN', A2MANUFACTURER.MANUNAME, A2SHIPPING.DESCRIPTION
FROM A2PRODUCT
INNER JOIN A2MANUFACTURER ON A2PRODUCT.MANUFACTURERCODE = A2MANUFACTURER.MANUCODE
INNER JOIN A2SHIPPING ON A2PRODUCT.SHIPPINGCODE = A2SHIPPING.SHIPPINGCODE
WHERE A2PRODUCT.ROWID IN (SELECT e.SOURCE_ROWID FROM A2ERROREVENT e WHERE FILTERID = 3 );
COMMIT;
/
INSERT INTO A2ERROREVENT ( ERRORID, SOURCE_ROWID, SOURCE_TABLE, FILTERID, DATETIME, ERRORCODE, ACTION )
SELECT A2ERROREVENT_SEQ.NEXTVAL AS ERRORID, ROWID, 'A2CUSTBRIS', 4, CURRENT_TIMESTAMP, 167, 'MODIFY'
FROM A2CUSTBRIS b
WHERE b.CUSTCATCODE IS NULL OR b.CUSTCATCODE NOT IN (SELECT c.CUSTCATCODE FROM A2CUSTCATEGORY c);
COMMIT;
/
INSERT INTO A2ERROREVENT ( ERRORID, SOURCE_ROWID, SOURCE_TABLE, FILTERID, DATETIME, ERRORCODE, ACTION )
SELECT A2ERROREVENT_SEQ.NEXTVAL AS ERRORID, ROWID, 'A2CUSTBRIS', 5, CURRENT_TIMESTAMP, 194, 'MODIFY'
FROM A2CUSTBRIS b
WHERE b.PHONE LIKE '% %' OR b.PHONE LIKE '%-%';
COMMIT;
/
INSERT INTO A2ERROREVENT ( ERRORID, SOURCE_ROWID, SOURCE_TABLE, FILTERID, DATETIME, ERRORCODE, ACTION )
SELECT A2ERROREVENT_SEQ.NEXTVAL AS ERRORID, ROWID, 'A2CUSTBRIS', 6, CURRENT_TIMESTAMP, 219, 'SKIP'
FROM A2CUSTBRIS b
WHERE LENGTH( b.PHONE ) != 10 AND b.PHONE NOT LIKE '% %' AND b.PHONE NOT LIKE '%-%';
COMMIT;
/
INSERT INTO A2ERROREVENT ( ERRORID, SOURCE_ROWID, SOURCE_TABLE, FILTERID, DATETIME, ERRORCODE, ACTION )
SELECT A2ERROREVENT_SEQ.NEXTVAL AS ERRORID, ROWID, 'A2CUSTBRIS', 7, CURRENT_TIMESTAMP, 227, 'MODIFY'
FROM A2CUSTBRIS b
WHERE b.GENDER IS NULL OR UPPER(b.GENDER) != 'M' AND UPPER(b.GENDER)!= 'F';
COMMIT;
/
INSERT INTO DWCUST (DWCUSTID, DWSOURCEIDBRIS, FIRSTNAME, SURNAME, GENDER, PHONE, POSTCODE, CITY, "STATE", CUSTCATNAME)
SELECT DWCUST_SEQ.NEXTVAL AS DWCUSTID, A2CUSTBRIS.CUSTID, A2CUSTBRIS.FNAME, A2CUSTBRIS.SNAME, UPPER (A2CUSTBRIS.GENDER), A2CUSTBRIS.PHONE, A2CUSTBRIS.POSTCODE, A2CUSTBRIS.CITY, A2CUSTBRIS."STATE", A2CUSTCATEGORY.CUSTCATNAME
FROM A2CUSTBRIS
INNER JOIN A2CUSTCATEGORY ON A2CUSTBRIS.CUSTCATCODE = A2CUSTCATEGORY.CUSTCATCODE
WHERE A2CUSTBRIS.ROWID NOT IN (SELECT e.SOURCE_ROWID FROM A2ERROREVENT e);
COMMIT;
/
INSERT INTO DWCUST (DWCUSTID, DWSOURCEIDBRIS, FIRSTNAME, SURNAME, GENDER, PHONE, POSTCODE, CITY, "STATE", CUSTCATNAME)
SELECT DWCUST_SEQ.NEXTVAL AS DWCUSTID, A2CUSTBRIS.CUSTID, A2CUSTBRIS.FNAME, A2CUSTBRIS.SNAME, UPPER (A2CUSTBRIS.GENDER), A2CUSTBRIS.PHONE, A2CUSTBRIS.POSTCODE, A2CUSTBRIS.CITY, A2CUSTBRIS."STATE", 'UNKNOWN'
FROM A2CUSTBRIS
WHERE A2CUSTBRIS.ROWID IN (SELECT e.SOURCE_ROWID FROM A2ERROREVENT e WHERE e.FILTERID = 4);
COMMIT;
/
INSERT INTO DWCUST (DWCUSTID, DWSOURCEIDBRIS, FIRSTNAME, SURNAME, GENDER, PHONE, POSTCODE, CITY, "STATE", CUSTCATNAME)
SELECT DWCUST_SEQ.NEXTVAL AS DWCUSTID, A2CUSTBRIS.CUSTID, A2CUSTBRIS.FNAME, A2CUSTBRIS.SNAME, UPPER (A2CUSTBRIS.GENDER), 
REGEXP_REPLACE( A2CUSTBRIS.PHONE, '-| ', null  ),
A2CUSTBRIS.POSTCODE, A2CUSTBRIS.CITY, A2CUSTBRIS."STATE", 'UNKNOWN'
FROM A2CUSTBRIS
WHERE A2CUSTBRIS.ROWID IN (SELECT e.SOURCE_ROWID FROM A2ERROREVENT e WHERE e.FILTERID = 5);
COMMIT;
/
INSERT INTO DWCUST (DWCUSTID, DWSOURCEIDBRIS, FIRSTNAME, SURNAME, GENDER, PHONE, POSTCODE, CITY, "STATE", CUSTCATNAME)
SELECT DWCUST_SEQ.NEXTVAL AS DWCUSTID, A2CUSTBRIS.CUSTID, A2CUSTBRIS.FNAME, A2CUSTBRIS.SNAME, GENDERSPELLING.NEWVALUE, A2CUSTBRIS.PHONE, A2CUSTBRIS.POSTCODE, A2CUSTBRIS.CITY, A2CUSTBRIS."STATE", A2CUSTCATEGORY.CUSTCATNAME
FROM A2CUSTBRIS
INNER JOIN A2CUSTCATEGORY ON A2CUSTBRIS.CUSTCATCODE = A2CUSTCATEGORY.CUSTCATCODE
INNER JOIN GENDERSPELLING ON UPPER(A2CUSTBRIS.GENDER) = GENDERSPELLING.INVALIDVALUE
WHERE A2CUSTBRIS.ROWID IN (SELECT e.SOURCE_ROWID FROM A2ERROREVENT e WHERE e.FILTERID = 7);
COMMIT;
/
INSERT INTO DWCUST (DWCUSTID, DWSOURCEIDBRIS, FIRSTNAME, SURNAME, GENDER, PHONE, POSTCODE, CITY, "STATE", CUSTCATNAME)
SELECT DWCUST_SEQ.NEXTVAL AS DWCUSTID, A2CUSTBRIS.CUSTID, A2CUSTBRIS.FNAME, A2CUSTBRIS.SNAME, 'U', A2CUSTBRIS.PHONE, A2CUSTBRIS.POSTCODE, A2CUSTBRIS.CITY, A2CUSTBRIS."STATE", A2CUSTCATEGORY.CUSTCATNAME
FROM A2CUSTBRIS
INNER JOIN A2CUSTCATEGORY ON A2CUSTBRIS.CUSTCATCODE = A2CUSTCATEGORY.CUSTCATCODE
WHERE A2CUSTBRIS.ROWID IN (SELECT e.SOURCE_ROWID FROM A2ERROREVENT e WHERE e.FILTERID = 7) 
AND UPPER(A2CUSTBRIS.GENDER) NOT IN (SELECT g.INVALIDVALUE FROM GENDERSPELLING g ) 
OR A2CUSTBRIS.GENDER IS NULL;
COMMIT;
/
MERGE INTO DWCUST DC
USING (SELECT * FROM A2CUSTMELB A2CM INNER JOIN A2CUSTCATEGORY A2CC ON 
A2CM.CUSTCATCODE=A2CC.CUSTCATCODE) CM
ON ( DC.FIRSTNAME=CM.FNAME AND DC.SURNAME=CM.SNAME AND DC.POSTCODE=CM.POSTCODE)
WHEN MATCHED THEN
UPDATE SET DC.DWSOURCEIDMELB=CM.CUSTID
WHEN NOT MATCHED THEN INSERT (DWCUSTID,DWSOURCEIDMELB,FIRSTNAME,SURNAME,GENDER,PHONE,POSTCODE,CITY,STSTE,CUSTCATNAME);
COMMIT;
/
INSERT INTO A2ERROREVENT( ERRORID, SOURCE_ROWID, SOURCE_TABLE, FILTERID, DATETIME, ERRORCODE, ACTION )
SELECT A2ERROREVENT_SEQ.NEXTVAL AS ERRORID, ROWID, 'A2SALEBRIS', 8, CURRENT_TIMESTAMP,258 , 'SKIP'
FROM A2SALEBRIS
WHERE PRODID NOT IN (SELECT DWSOURCEID FROM DWPROD) OR PRODID IS NULL;  
COMMIT
/

INSERT INTO A2ERROREVENT( ERRORID, SOURCE_ROWID, SOURCE_TABLE, FILTERID, DATETIME, ERRORCODE, ACTION )
SELECT A2ERROREVENT_SEQ.NEXTVAL AS ERRORID, ROWID, 'A2SALEBRIS', 9, CURRENT_TIMESTAMP,262 , 'SKIP'
FROM A2SALEBRIS
WHERE NOT EXISTS
(SELECT NULL FROM DWCUST  WHERE A2SALEBRIS.CUSTID=DWCUST.DWSOURCEIDBRIS);  
COMMIT;
/
INSERT INTO A2ERROREVENT( ERRORID, SOURCE_ROWID, SOURCE_TABLE, FILTERID, DATETIME, ERRORCODE, ACTION )
SELECT A2ERROREVENT_SEQ.NEXTVAL AS ERRORID, ROWID, 'A2SALEBRIS', 10, CURRENT_TIMESTAMP,294 , 'MODIFY'
FROM A2SALEBRIS
WHERE SALEDATE>SHIPDATE;
COMMIT;
/
INSERT INTO A2ERROREVENT( ERRORID, SOURCE_ROWID, SOURCE_TABLE, FILTERID, DATETIME, ERRORCODE, ACTION )
SELECT A2ERROREVENT_SEQ.NEXTVAL AS ERRORID, ROWID, 'A2SALEBRIS', 11, CURRENT_TIMESTAMP,312 , 'MODIFY'
FROM A2SALEBRIS
WHERE UNITPRICE IS NULL;
COMMIT:
/
INSERT INTO DWSALE(DWSALEID, DWCUSTID, DWPRODID, DWSOURCEIDBRIS, QTY, SALE_DWDATEID, SHIP_DWDATEID, SALEPRICE) 
SELECT DWSALE_SEQ.NEXTVAL,(SELECT DWCUSTID FROM DWCUST WHERE DWSOURCEMELB=CUSTID),
(SELECT DWPRODID FROM DWPROD WHERE DWSOURCEID=PRODID),SALEID,QTY,
(SELECT DWPRODID FROM DWDATE WHERE DATEVALUE=DALEDATE),
(SELECT DATAKEY FROM DWDATE WHERE DATAVALUE=SHIPDATE),UNITPRICE
FROM A2SALEMELB          
WHERE ROWID NOT IN (SELECT SOURCE_ROWID FROM A2ERROREVENT);
COMMIT;













