SET SERVEROUTPUT ON;
CLEAR SCREEN;
SELECT * FROM A2PRODUCT;
SELECT * FROM A2PRODCATEGORY;
SELECT * FROM A2ERROREVENT;
SELECT * FROM A2MANUFACTURER;
SELECT * FROM A2SHIPPING;

SELECT A2PRODUCT.PRODID, A2PRODUCT.PRODNAME, A2PRODUCT.MAXQTY, A2PRODCATEGORY.CATEGORYNAME, A2MANUFACTURER.MANUNAME, A2SHIPPING.DESCRIPTION
FROM A2PRODUCT 
INNER JOIN A2PRODCATEGORY ON A2PRODUCT.PRODCATEGORY = A2PRODCATEGORY.PRODUCTCATEGORY
INNER JOIN A2MANUFACTURER ON A2PRODUCT.MANUFACTURERCODE = A2MANUFACTURER.MANUCODE
INNER JOIN A2SHIPPING ON A2PRODUCT.SHIPPINGCODE = A2SHIPPING.SHIPPINGCODE
WHERE A2PRODUCT.ROWID NOT IN (SELECT e.SOURCE_ROWID FROM A2ERROREVENT e);
SELECT * FROM DWPROD;
SELECT * FROM A2CUSTBRIS b WHERE b.CUSTCATCODE NOT IN (SELECT c.CUSTCATCODE FROM A2CUSTCATEGORY c);

SELECT * FROM A2ERROREVENT;
SELECT * FROM A2CUSTBRIS b WHERE b.GENDER IS NULL OR UPPER(b.GENDER) != 'M' AND UPPER(b.GENDER)!= 'F';
SELECT * FROM A2CUSTCATEGORY;
SELECT * FROM DWCUST;

